stages:
  - test
  - release

before_script:
  - git config user.email $GITLAB_USER_EMAIL
  - git config user.name $GITLAB_USER_NAME
  - git remote set-url origin git@gitlab.corp.mail.ru:qa/yoda.git
  - git checkout -B master
  - npm install

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm run lint
