/** Список хелперов */
export default {
	// old
	'spam': 0,
	'nospam': 1,
	'cloud': 7,
	'mailtoObserver': 12,
	'filesearch': 14,
	'collector': 15,
	'multiAuth': 22,
	'attachFromCloud': 29,
	'save-to-cloud': 32,

	// new
	'mailbox-sort': 33,
	'mailbox-sort-plate': 34,
	'promo-layer-edit': 35,
	'promo-balloon-edit-doc': 36,
	'promo-balloon-edit-excel': 37,
	'promo-balloon-edit-pp': 38,

	'filters-processing': 42,
	'septemper-the-first': 43,
	'phone_verify': 44,
	'phone_access': 45,
	'email_access': 46,
	'secret_question': 47,
	'compose-templates-balloon-reply': 48,
	'compose-templates-balloon': 49,

	'alternate-viewer-for-doc': 51,
	'alternate-viewer-for-excel': 52,
	'alternate-viewer-for-pp': 53,
	'verify-phone-plate': 54,
	'archive-folder': 55,
	'expand-archive': 56,
	'promo-balloon-create-event-button': 57,
	'tester': 59,

	'thread-promo-letter': 60,
	'compose-use-api-v1': 61,
	'compose-drop-image-in-editor': 62,
	'threads': 63,
	'letters-head-actions': 65,
	'theme-weather': 66,
	'theme-avengers': 67,
	'left-col-ad': 68,
	'alias': 69,

	'mailbox-sort-informer': 70,
	'tutorial-widget': 72,
	'tutorial-widget-app': 73,
	'tutorial-widget-signature': 74,
	'edit-attach': 76,

	'mailbox-sort-plate-exp': 80,
	'fast-reply-landmark': 81,
	'link-snippets-readmsg': 82,
	'notifications-megafon-confirmed': 83,
	'threads_announcements_enable': 84,
	'tutorial-widget-state': 85,
	'newyear-afisha-balloon': 86,
	'newyear2016-letter': 88,
	'horoscope-balloon': 89,

	'armata-balloon': 91,
	'balloon-cleaner': 93,
	'balloon-pins': 94,
	'balloon-emoji': 95,
	'balloon-inline-image': 96,
	'balloon-theme-zenit': 97,
	'balloon-theme-space': 98,
	'compose-new-design': 99,

	'balloon-theme-iihf2016': 100,
	'balloon-theme-uefa2016': 101,
	'balloon-cleaner-archive': 103,
	'balloon-theme-rio2016': 104,
	'balloon-filters': 105,
	'balloon-html-signature': 107,
	'balloon-theme-cska': 108,
	'promo:mailbox-parsing': 109,

	'promo:mobile-apps': 110,
	'promo:threads': 111,
	'swa-promo-totp': 112,
	'push-notifications-balloon': 113,
	'news-widget-seen': 114,
	'news-widget-promo': 115,
	'bonus-seen': 116,
	'bonus-promo': 117,
	'bonus-promo-ny': 118,
	'sound-notifications': 119,

	'transaction-category': 120,
	'balloon-compose-schedule': 121,
	'feedback-nps': 125,
	'announcement-signature': 126,
	'announcement-mobile': 127,
	'announcement-anonim': 128,
	'beepcar-letter1': 129,

	'beepcar-letter2': 130,
	'necromancer-letter-app': 131,
	'necromancer-letter-features': 132,
	'beepcar-letter3': 133,
	'beepcar-letter4': 134,
	'autotest': 135,
	'beta-user-widget-seen': 136,
	'security-letter': 137,
	'promo:bonus': 138,
	'balloon-unsubscribe': 139,

	'bonus-counter-seen': 140,
	'bonus-counter-last-click': 141,
	'announcement-transaction-category': 142,
	'beepcar-letter5': 143,
	'beepcar-letter5-split1': 144,
	'beepcar-letter5-split2': 145,
	'fines': 146,
	'club-seen': 147,
	'beepcar-letter-azerbaijan': 148,
	'beepcar-letter-estonia': 149,

	'beepcar-letter-kazakhstan': 150,
	'beepcar-letter-lithuania': 151,
	'beepcar-letter-latvia': 152,
	'beepcar-letter-moldova': 153,
	'beepcar-letter-turkmenistan': 154,
	'beepcar-letter-kyrgyzstan': 155,
	'beepcar-letter-uzbekistan': 156,
	'beepcar-letter-georgia': 157,
	'announcement-taxes': 158,
	'segmented-promo': 159,

	'announcement-fines': 160,
	'swa-promo-phones': 161,
	'metathreads': 162,
	'money-send': 163,
	'balloon-beta-settings': 164,
	'announcement-mobile-payments': 165,
	'announcement-remove-old-newsletters': 166,
	'use-3pane': 167,
	'cleanmaster-announcement': 168,
	'announcement-metathreads-survey': 169
};
