#!/usr/bin/env bash

# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.
# The hook's purpose is to edit the commit message file.
# If the hook fails with a non-zero status, the commit is aborted.
#
# Example
#
# git rev-parse --abbrev-ref HEAD
# deploy
#
# git commit -m 'init commit'
#
# git show
# commit 1abc2f131d8e20c306ecce8bb95b02e365b0af60 (HEAD, refs/heads/mail-16043)
# Author: Alexander Abashkin <monolithed@gmail.com>
# Date:   Mon Jun 17 18:12:15 2013 +0400
#
#    [DEPLOY] init commit
#
#
# .git/COMMIT_EDITMSG

branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null);
output=$(tr [:lower:] [:upper:] <<< [${branch}]);

if [ -n ${branch} ] && ! [[ $(< $1) =~ $output ]] && [ ${branch} != 'master' ];
	then echo "$output $(< $1)" > $1;
fi
